### ISSUE TITLE
Zygote.forward not defined

### ISSUE THREAD

**Issue by mhangaard** [willtebbutt/BayesianLinearRegressors.jl#4]
but back_rand also doesn't seem to be used, so the block can be deleted and then the usage example runs.
was using Zygote 0.4.1 and Julia 1.2.0

**Comment by willtebbutt** [comment]
Ah okay, the Zygote interface changed. Would you mind trying changing `Zygote.forward` to `Zygote.pullback` and seeing if it runs?

**Comment by mhangaard** [comment]
> Ah okay, the Zygote interface changed. Would you mind trying changing `Zygote.forward` to `Zygote.pullback` and seeing if it runs?

Yes that runs.

**Comment by willtebbutt** [comment]
Fantastic. I'll update the readme. Thanks!
