### ISSUE TITLE
Question about the syntax

### ISSUE THREAD

**Issue by pflashgary** [willtebbutt/BayesianLinearRegressors.jl#5]
https://github.com/willtebbutt/BayesianLinearRegressors.jl/blob/c7c782d9e20bda92c095ffcbcf531d8f9291c069/src/bayesian_linear_regression.jl#L29-L31

I've tried finding the syntax in the Julia docs but I can't find it and don't know the name. Would you mind explaining what's happening on these lines?

**Comment by willtebbutt** [comment]
From a Julia perspective, this is "calling" the `BayesianLinearRegressor` object.

From a `BayesianLinearRegressors` perspective, you should interpret this as specifying the inputs `X` at which you're going to observe `blr`, and the covariance `Σy ` of the observation noise under which they will be observed -- if you provide a real value `σ²` it is assumed that the covariance is `σ² I`.

So let `f` be some `BayesianLinearRegressor`, then you can write
```julia
# Specify locations to make observations
fx = f(x, σ²)

# sample from the prior:
y = rand(fx)

# compute the log marginal probability of `y` under the prior:
logpdf(fx, y)
```

Does this answer your question?

**Comment by pflashgary** [comment]
Thanks so much for clarifying . I understand the Bayesian perspective but not the Julia syntax very well.
I assume you're function overloading on lines 29-31?

**Comment by pflashgary** [comment]
Just read the link. makes total sense now, appreciate it.
